### ISSUE TITLE
[Question]Why does Run-AlPipeline bind a volume to c:\sources inside the container?

### ISSUE THREAD

**Issue by staedter** [microsoft/navcontainerhelper#1632]
**Describe the issue**
We are using the Hello-World pipeline templates for some of our CI/CD-processes and I was trying to optimize the performance while running on self-hosted agents which always use the same target version because it is a dedicated build machine for a specific customer.

That is why I thought it should be possible to run the AL-Pipeline with the "-keepContainer" flag activated. Furthermore I just commented out the pipeline CleanUp Task, so that the container is still running.

The problem is now, that the Azure DevOps Job fails while initializing with the following error: 
![image](https://user-images.githubusercontent.com/46670623/105047552-c569a380-5a6a-11eb-913d-8fc6abe4c364.png)

![image](https://user-images.githubusercontent.com/46670623/105047767-0c579900-5a6b-11eb-8aa6-e3448799f277.png)

I think the problem here is, that the running container is somehow locking the agent working folder and I guess it has something to do with the fact, that there is a volume that is actively bound to the $basefolder in the Run-AlPipelines.ps1
```
$Parameters += @{
        "accept_eula" = $true
        "containerName" = $containerName
        "imageName" = $imageName
        "artifactUrl" = $artifactUrl
        "useGenericImage" = $useGenericImage
        "Credential" = $credential
        "auth" = 'UserPassword'
        "vsixFile" = $vsixFile
        "updateHosts" = $true
        "licenseFile" = $licenseFile
        "EnableTaskScheduler" = $enableTaskScheduler
        "AssignPremiumPlan" = $assignPremiumPlan
        "MemoryLimit" = $memoryLimit
        "additionalParameters" = @("--volume ""$($baseFolder):c:\sources""")
    }
```
I suspect this additionalParameters to be the culprit. And I was wondering where or why this volume is needed in the first place? Maybe we could also deactivate this dynamically with a parameter in the Run-AlPipeline function?

Any information / help would be greatly appreciated :)

**Scripts used to create container and cause the issue**
```
Param(
    [Parameter(Mandatory=$false)]
    [ValidateSet('AzureDevOps','GithubActions','GitLab')]
    [string] $environment = 'AzureDevOps',
    [Parameter(Mandatory=$true)]
    [string] $version,
    [Parameter(Mandatory=$false)]
    [int] $appBuild = 0,
    [Parameter(Mandatory=$false)]
    [int] $appRevision = 0
)

if ($environment -eq "AzureDevOps") {
    $buildArtifactFolder = $ENV:BUILD_ARTIFACTSTAGINGDIRECTORY
}
elseif ($environment -eq "GitHubActions") {
    $buildArtifactFolder = Join-Path $ENV:GITHUB_WORKSPACE "output"
    New-Item $buildArtifactFolder -ItemType Directory | Out-Null
}

$baseFolder = (Get-Item (Join-Path $PSScriptRoot "..")).FullName
. (Join-Path $PSScriptRoot "Read-Settings.ps1") -environment $environment -version $version
. (Join-Path $PSScriptRoot "Install-BcContainerHelper.ps1") -bcContainerHelperVersion $bcContainerHelperVersion -genericImageName $genericImageName

$params = @{}
$insiderSasToken = "$ENV:insiderSasToken"
$licenseFile = "$ENV:licenseFile"
$codeSigncertPfxFile = "$ENV:CodeSignCertPfxFile"
if (!$doNotSignApps -and $codeSigncertPfxFile) {
    if ("$ENV:CodeSignCertPfxPassword" -ne "") {
        $codeSignCertPfxPassword = try { "$ENV:CodeSignCertPfxPassword" | ConvertTo-SecureString } catch { ConvertTo-SecureString -String "$ENV:CodeSignCertPfxPassword" -AsPlainText -Force }
        $params = @{
            "codeSignCertPfxFile" = $codeSignCertPfxFile
            "codeSignCertPfxPassword" = $codeSignCertPfxPassword
        }
    }
    else {
        $codeSignCertPfxPassword = $null
    }
}

$allTestResults = "testresults*.xml"
$testResultsFile = Join-Path $baseFolder "TestResults.xml"
$testResultsFiles = Join-Path $baseFolder $allTestResults
if (Test-Path $testResultsFiles) {
    Remove-Item $testResultsFiles -Force
}

Run-AlPipeline @params `
    -pipelinename $pipelineName `
    -containerName $containerName `
    -imageName $imageName `
    -artifact $artifact.replace('{INSIDERSASTOKEN}',$insiderSasToken) `
    -memoryLimit $memoryLimit `
    -baseFolder $baseFolder `
    -licenseFile $LicenseFile `
    -installApps $installApps `
    -previousApps $previousApps `
    -appFolders $appFolders `
    -testFolders $testFolders `
    -doNotRunTests:$doNotRunTests `
    -testResultsFile $testResultsFile `
    -testResultsFormat 'JUnit' `
    -installTestFramework:$installTestFramework `
    -installTestLibraries:$installTestLibraries `
    -installPerformanceToolkit:$installPerformanceToolkit `
    -enableCodeCop:$enableCodeCop `
    -enableAppSourceCop:$enableAppSourceCop `
    -enablePerTenantExtensionCop:$enablePerTenantExtensionCop `
    -enableUICop:$enableUICop `
    -azureDevOps:($environment -eq 'AzureDevOps') `
    -gitLab:($environment -eq 'GitLab') `
    -AppSourceCopMandatoryAffixes $appSourceCopMandatoryAffixes `
    -AppSourceCopSupportedCountries $appSourceCopSupportedCountries `
    -additionalCountries $additionalCountries `
    -buildArtifactFolder $buildArtifactFolder `
    -CreateRuntimePackages:$CreateRuntimePackages `
    -appBuild $appBuild -appRevision $appRevision `
    -keepContainer

if ($environment -eq 'AzureDevOps') {
    Write-Host "##vso[task.setvariable variable=TestResults]$allTestResults"
}
```
```
trigger:
- master
- dev

pool: anaptis

variables:
- group: APT KeyVault

jobs:
- job: Build
  timeoutInMinutes: 300
  variables:
    build.clean: all
    platform: x64
    version: 'ci'
    appVersion: '2.0'
    appBuild: $(Build.BuildID)
    appRevision: 0
    skipComponentGovernanceDetection: True

  steps:
  - task: PowerShell@2
    displayName: 'Set BuildNumber'
    inputs:
      targetType: inline
      script: 'Write-Host "##vso[build.updatebuildnumber]$(appVersion).$(appBuild).$(appRevision)"'

  - task: PowerShell@2
    displayName: 'Run Pipeline'
    env:
      InsiderSasToken: '$(InsiderSasToken)'
      LicenseFile: '$(LicenseFile)'
      CodeSignCertPfxFile: '$(CodeSignCertPfxFile)'
      CodeSignCertPfxPassword: '$(CodeSignCertPfxPassword)'
    inputs:
      targetType: filePath
      filePath: 'scripts\DevOps-Pipeline.ps1'
      arguments: '-environment "AzureDevOps" -version "$(version)" -appBuild $(appBuild) -appRevision $(appRevision)'
      failOnStderr: true

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: and(succeeded(),ne(variables['TestResults'],''))
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '$(testResults)'
      failTaskOnFailedTests: true

  - task: PowerShell@2
    displayName: 'Copy deployment scripts'
    inputs:
      targetType: inline
      script: 'Copy-Item -Path scripts\Deploy-OnPremApp.ps1 -Destination $(Build.ArtifactStagingDirectory); Copy-Item -Path App\app.json -Destination $(Build.ArtifactStagingDirectory)\Apps '
      failOnStderr: true
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: output

#  - task: PowerShell@2
#    displayName: 'Cleanup'
#    condition: always()
#    inputs:
#      targetType: filePath
#      filePath: 'scripts\Cleanup.ps1'
#      arguments: '-environment "AzureDevOps"'
#      failOnStderr: false
```

**Full output of scripts**
```
Starting: Initialize job
Agent name: 'CUSTOMER-a'
Agent machine name: 'BUILD-CUSTOMER'
Current agent version: '2.179.0'
Agent running as: 'agent'
Prepare build directory.
##[error]The process cannot access the file 'C:\agent1\_work\1\s' because it is being used by another process.
Finishing: Initialize job
```

**Additional context**
- the problem appears when we run the pipeline a second time, because than the container is still running and locking the agent working folder
