### ISSUE TITLE
Error in applicationInsightsConnectionString

### ISSUE THREAD

**Issue by ivanrlg** [microsoft/navcontainerhelper#2218]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I am trying to run the unit tests on Azure Devops, using the "cicd workshop".
2 weeks ago maybe everything was working correctly, until we decided to update the "settings" to use version 19 of BC.

The problem we have is an error with the applicationInsightsConnectionString, both the Test application, the App and the "previusApp" are updated to use
"applicationInsightsConnectionString": "11111111-2222-3333-4444-555555555555"

The error occurs when the Apps are being compiled in the "Run Pipeline"

Is it possible that the script needs to be updated?

**Scripts used to create container and cause the issue**
```
  - task: PowerShell@2
    displayName: 'Run Pipeline'
    env:
      InsiderSasToken: '$(InsiderSasToken)'
      LicenseFile: '$(LicenseFileBC19)'
      CodeSignCertPfxFile: '$(CodeSignCertPfxFile)'
      CodeSignCertPfxPassword: '$(CodeSignCertPfxPassword)'
      ApplicationInsightsKey: '$(applicationInsightsKey)'
    inputs:
      targetType: filePath
      filePath: 'scripts\DevOps-Pipeline.ps1'
      arguments: '-environment "AzureDevOps" -version "$(version)" -appBuild $(appBuild) -appRevision $(appRevision)'
      failOnStderr: true
```

**Full output of scripts**
```
Compiling...
.\alc.exe /project:"c:\sources\app" /packagecachepath:"c:\sources\.packages" /out:"c:\sources\.output\Plur-E.com, Corp_Plur-E App For Business Central_1.0.44.0.app" /analyzer:C:\build\vsix\extension\bin\Analyzers\Microsoft.Dynamics.Nav.AppSourceCop.dll /analyzer:C:\build\vsix\extension\bin\Analyzers\Microsoft.Dynamics.Nav.UICop.dll /assemblyprobingpaths:"C:\Program Files (x86)\Microsoft Dynamics NAV\190\RoleTailored Client","C:\Program Files\Microsoft Dynamics NAV\190\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\Windows\Microsoft.NET\Assembly","C:\Test Assemblies\Mock Assemblies"
Microsoft (R) AL Compiler version 8.2.8.28400
Copyright (C) Microsoft Corporation. All rights reserved

##[warning]c:\sources\app\app.json(39,5): warning AL0667: 'applicationInsightsKey' is being deprecated in the versions: '7.2' or greater. This property is being deprecated in favor of 'applicationInsightsConnectionString'. This warning will become an error in a future release.
##[error]c:\sources\app\app.json(39,5): error AL1074: Both 'applicationInsightsKey' and 'applicationInsightsConnectionString' are added. You should use the 'applicationInsightsConnectionString' property and remove the 'applicationInsightsKey' property.
App generation failed with exit code 1

NavContainerHelper is version 0.6.5.7
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
...
```

**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by ivanrlg** [comment]
I already got the error, you have to update part of the previous script as follows:
```
- task: PowerShell @ 2
     displayName: 'Run Pipeline'
     env:
       InsiderSasToken: '$ (InsiderSasToken)'
       LicenseFile: '$ (LicenseFileBC19)'
       CodeSignCertPfxFile: '$ (CodeSignCertPfxFile)'
       CodeSignCertPfxPassword: '$ (CodeSignCertPfxPassword)'
       applicationInsightsConnectionString: '$ (applicationInsightsKey)'
     inputs:
       targetType: filePath
       filePath: 'scripts \ DevOps-Pipeline.ps1'
       arguments: '-environment "AzureDevOps" -version "$ (version)" -appBuild $ (appBuild) -appRevision $ (appRevision)'
       failOnStderr: true
```
