### ISSUE TITLE
Enabling SSL for different services fails in container

### ISSUE THREAD

**Issue by michvllni** [microsoft/navcontainerhelper#2263]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When I try to enable SSL for different services (OData, SOAP, Developer, Snapshot), I get the following error in the container:

![image](https://user-images.githubusercontent.com/45660891/149305386-eff0939f-7d2d-4f2f-8235-9c3d540bb101.png)

The issue seems to be that the user has a space. I could not reproduce this on my host machine, mainly because it is in german and NT Authority in german is called "NT-AUTORITÄT" without a space.

When I allow the url manually with `netsh http add urlacl url=https://+:7049/BC 'user=NT AUTHORITY\SYSTEM'` it afterwards works without issues

I were able to reproduce this in a cronus 19.2 container

**Scripts used to create container and cause the issue**
```powershell
New-BCImage -addFontsFromPath: mypath -skipDatabase: False -artifactUrl: https://bcartifacts.azureedge.net/onprem/19.2.32968.33504/de -isolation: process -baseImage: mcr.microsoft.com/businesscentral:10.0.17763.2366 -filesOnly: False -memory: 20G  -multitenant: False -imageName: containerhelper:server-19.2
```
I'm using compose to run the container with the following configuration:
```yml
networks:
  dev:
    external:
      name: nat
services:
  cronus:
    volumes:
    - C:\ContainerService\cronus\DLL\Assembly:C:\assembly
    - C:\ContainerService\cronus\Tausch:C:\ContainerService\cronus\Tausch
    - C:\ContainerService\cronus\DLL\Service ohne newsystem:C:\service
    - C:\ProgramData\BcContainerHelper:C:\BcContainerHelper
    - C:\ContainerService\cronus\DLL\infoma newsystem:C:\Program Files\Microsoft Dynamics NAV\190\Service\Add-ins\infoma newsystem
    container_name: cronus
    networks:
    - dev
    mem_limit: 8G
    restart: unless-stopped
    ports:
    - 1437:80
    - 1438:7049
    - 1439:7047
    - 1440:7048
    - 1441:1433
    - 1442:7083
    dns:
    - 8.8.8.8
    - 8.8.4.4
    image: containerhelper:server-19.2
    environment:
    - Accept_eula=Y
    - UseSSL=N
    - ACCEPT_OUTDATED=Y
    - REMOVEPASSWORDKEYFILE=N
    - auth=NavUserPassword
    - PasswordKeyFile=C:\ContainerService\cronus\Tausch\nav.key
    - username=mivi
    - securePassword=mysecurepasswordasbase64
    - licenseFile=C:\ContainerService\cronus\Tausch\license.flf
    - customNavSettings=PublicWebBaseUrl=http://localhost:1437/BC,SqlLongRunningThreshold=10000,AllowSessionWhileSyncAndDataUpgrade=True,EnableTaskScheduler=True,ClientServicesReconnectPeriod=01:00:00
version: "3.3"

```
**Full output of scripts**
Initializing...
Starting Container
Hostname is 8eb97efa01eb
PublicDnsName is 8eb97efa01eb
Using NavUserPassword Authentication
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 1602B35789D9C9D08B490ECC878DA08C90771E23
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting PublicWebBaseUrl to http://localhost:1437/BC
Setting SqlLongRunningThreshold to 10000
Setting AllowSessionWhileSyncAndDataUpgrade to True
Setting EnableTaskScheduler to True
Setting ClientServicesReconnectPeriod to 01:00:00
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'C:\ContainerService\cronus\Tausch\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating mivi as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements.
It should be at least 8 characters long and contain at least one uppercase
letter, one lowercase letter, and one number.
Container IP Address: 172.26.159.238
Container Hostname  : 8eb97efa01eb
Container Dns Name  : 8eb97efa01eb
Web Client          : http://8eb97efa01eb/BC/
Dev. Server         : http://8eb97efa01eb
Dev. ServerInstance : BC

Files:
http://8eb97efa01eb:8080/ALLanguage.vsix

Container Total Physical Memory is 32.0Gb
Container Free Physical Memory is 11.3Gb

Initialization took 108 seconds
Ready for connections!
Starting EventLog Monitor
Monitoring EventSources from EventLog[Application]:
- MicrosoftDynamicsNAVClientClientService
- MicrosoftDynamicsNAVClientWebClient
- MicrosoftDynamicsNavServer$BC
- MSSQL$SQLEXPRESS

Generating desktop shortcuts
```
NavContainerHelper is version 3.0.0.0
NavContainerHelper is running as administrator: yes
Host is Microsoft Windows Server 2019 1809 17763.2366
Docker Client Version is 18.09.1
Docker Server Version is 18.09.1
...
```

**Screenshots**

**Additional context**
- does it happen all the time? Yes
- did it use to work? I cannot confirm this. I just recently tried this for the first time
