### ISSUE TITLE
Database Collation does not match the one in collation.txt

### ISSUE THREAD

**Issue by michvllni** [microsoft/navcontainerhelper#2420]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
A clear and concise description of what the issue is.
While my collation.txt says the database collation is Latin1_General_100_CS_AS, SSMS shows me that the collation is SQL_Latin1_General_CP1_CI_AS.
Im creating the docker image with New-BCImage (command following later) and then add a bak file in a wrapping dockerfile.
To run the container I use docker-compose pointing to the bak file to restore.
**Scripts used to create container and cause the issue**
```powershell
New-BcImage -skipDatabase -artifactUrl https://bcartifacts.azureedge.net/onprem/19.5.36567.36700/de -isolation process -baseImage mcr.microsoft.com/businesscentral:10.0.17763.2803 -memory 20G -imageName base:19.5
```
this image then gets wrapped in a dockerfile to add the bak (saves some layers when creating several images with different baks)
```dockerfile
FROM base:19.5
COPY ["/database", "C:/Program Files/Microsoft Dynamics NAV/190/database"]
WORKDIR /
ENTRYPOINT ["powershell.exe","C:\\run\my\start.ps1"]
```
```yml
networks:
  dev:
    external:
      name: nat
services:
  DEV:
    volumes:
    - C:\ProgramData\BcContainerHelper:C:\BcContainerHelper
    container_name: DEV
    networks:
    - dev
    mem_limit: 25G
    restart: unless-stopped
    ports:
    - 1337:80
    - 1338:7049
    - 1339:7047
    - 1340:7048
    - 1369:1433
    - 1341:7083
    dns:
    - 8.8.8.8
    - 8.8.4.4
    image: myimage:19.5
    environment:
    - Accept_eula=Y
    - UseSSL=N
    - ACCEPT_OUTDATED=Y
    - REMOVEPASSWORDKEYFILE=N
    - auth=NavUserPassword
    - PasswordKeyFile=C:\path\to\nav.key
    - username=myusername
    - securePassword=mysecurepassword
    - bakfile=C:\Program Files\Microsoft Dynamics NAV\190\database\database.bak
    - licenseFile=C:\path\to\license.flf
    - customNavSettings=PublicWebBaseUrl=http://localhost:1337/BC,SqlLongRunningThreshold=10000,AllowSessionWhileSyncAndDataUpgrade=True,EnableTaskScheduler=True,ClientServicesReconnectPeriod=01:00:00
version: "3.3"

```
**Full output of scripts**
```
Generic Tag: 1.0.2.1
Container OS Version: 10.0.17763.2803 (ltsc2019)
Host OS Version: 10.0.17763.2803 (ltsc2019)
Using process isolation
Files in F:\bcartifacts.cache\x0zckvo3.444\my:
- my
Copying Platform Artifacts
F:\bcartifacts.cache\onprem\19.5.36567.36700\platform
Copying ConfigurationPackages
F:\bcartifacts.cache\onprem\19.5.36567.36700\de\ConfigurationPackages
Copying Applications
F:\bcartifacts.cache\onprem\19.5.36567.36700\de\Applications
F:\bcartifacts.cache\x0zckvo3.444
Adding fonts
Sending build context to Docker daemon  1.209GB

Step 1/8 : FROM mcr.microsoft.com/businesscentral:10.0.17763.2803
 ---> 3922e9c4c27a
Step 2/8 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onprem/19.5.36567.36700/de filesOnly=False
 ---> Running in 8412aec54be3
Removing intermediate container 8412aec54be3
 ---> 82199760b354
Step 3/8 : COPY my /run/
 ---> bb922f489656
Step 4/8 : COPY NAVDVD /NAVDVD/
 ---> cad813b2298a
Step 5/8 : COPY Fonts /Fonts/
 ---> 391ad141b27f
Step 6/8 : RUN . C:\Fonts\AddFonts.ps1
 ---> Running in 626d4202ac42
Installing font 'c:\Windows\Fonts\3OF9.TTF' succeeded
Installing font 'c:\Windows\Fonts\arial.ttf' succeeded
Installing font 'c:\Windows\Fonts\arialbd.ttf' succeeded
Installing font 'c:\Windows\Fonts\arialbi.ttf' succeeded
Installing font 'c:\Windows\Fonts\ariali.ttf' succeeded
Installing font 'c:\Windows\Fonts\ARIALN.TTF' succeeded
Installing font 'c:\Windows\Fonts\ARIALNB.TTF' succeeded
Installing font 'c:\Windows\Fonts\ARIALNBI.TTF' succeeded
Installing font 'c:\Windows\Fonts\ARIALNI.TTF' succeeded
Installing font 'c:\Windows\Fonts\ariblk.ttf' succeeded
Installing font 'c:\Windows\Fonts\ARLRDBD.TTF' succeeded
Installing font 'c:\Windows\Fonts\FRE3OF9X.TTF' succeeded
Installing font 'c:\Windows\Fonts\OCRB.ttf' succeeded
Installing font 'c:\Windows\Fonts\segoeui.ttf' succeeded
Installing font 'c:\Windows\Fonts\segoeuib.ttf' succeeded
Removing intermediate container 626d4202ac42
 ---> d4b1fdfe9e97
Step 7/8 : RUN \Run\start.ps1 -installOnly
 ---> Running in f4194668d166
Using installer from C:\Run\150-new
Installing Business Central
Installing from DVD
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
Starting Internet Information Server
Copying Service Tier Files
C:\NAVDVD\ServiceTier\Program Files
C:\NAVDVD\ServiceTier\System64Folder
Copying PowerShell Scripts
C:\NAVDVD\WindowsPowerShellScripts\Cloud\NAVAdministration
C:\NAVDVD\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
C:\NAVDVD\WebClient\Microsoft Dynamics NAV
Copying Client Files
C:\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV
C:\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV
C:\NAVDVD\LegacyDlls\systemFolder
Copying ModernDev Files
C:\NAVDVD
C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\NAVDVD\ConfigurationPackages
Copying Test Assemblies
C:\NAVDVD\Test Assemblies
Copying Applications
C:\NAVDVD\Applications
Installation took 44 seconds
Installation complete
Removing intermediate container f4194668d166
 ---> 49f2703a8793
Step 8/8 : LABEL legal="http://go.microsoft.com/fwlink/?LinkId=837447"       created="202204220640"       nav=""       cu=""       skipdatabase="Y" country="de"       version="19.5.36567.36700"       platform="19.0.36528.36625"
 ---> Running in 6a36762cc48d
Removing intermediate container 6a36762cc48d
 ---> ade157d85459
Successfully built ade157d85459
Successfully tagged base:19.5
...
```

**Screenshots**
![image](https://user-images.githubusercontent.com/45660891/164627399-5181b048-1939-435e-ba23-ff90cf6abf4c.png)
![image](https://user-images.githubusercontent.com/45660891/164627463-69c10c0e-e8cc-4bdf-b000-697c667cdaaa.png)

**Additional context**
- does it happen all the time? yes
- did it use to work? not sure
