### ISSUE TITLE
AL-GO CI/CD workflow for 3 previous BC versions

### ISSUE THREAD

**Issue by nemanja899** [microsoft/navcontainerhelper#3098]
Hi not necessary an issue since it does not say that I can overwrite RunPipeline.ps1 script.

But my idea it to create 3 different containers on Azure VM's for each BC version, since our plan is to support those versions for our clients. Already configured AL-GO to be self-hosted and connected them to Azure VM.

Do you have any idea how to make that work. Do I have to customize CompileAppInBcContainer.ps1 and NewBcContainer.ps1 since I can't overwrite  RunPipeline.ps1? 
Thank you. :)

**Comment by freddydk** [comment]
Is this a ContainerHelper question or an AL-Go question?

**Comment by nemanja899** [comment]
I guess it's a bit of both since I am not sure how could I create this workflow.

**Comment by freddydk** [comment]
I would like to understand what you want to achieve.
Is the goal to ensure that the "same" app version works for all BC versions for which it is supported?
Or is the goal to have different editions of the same app version for all BC versions for which the app is supported?

Today we have 22.2 as the latest release.
Your app needs to be compatible for 20.0 and forward - is that correctly understood?
What is the application dependency in app.json?
What is the runtime property in app.json?
Do you use preprocessor directives to make the app different for different versioins or is the app really the same for all versions?

**Comment by nemanja899** [comment]
Goal is to ensure same app version works for all BC versions.
Yes you understood correctly. :)
Run time is "9.0" , "aplication":"20.0.0.0" if current version is 22 and when 23 comes out we will support from 21 version and onward.
Application dependence is 20.0.0.0.
App is the same for all versions.

**Comment by marknitek** [comment]
We do exactly that in our build process. But we use Azure DevOps and have a custom build process / scripts based on freddys initial scripts but heavily modified, imporoved and customized. 

Maybe i can assist with some code snippets.

The main approach was to use a single code base where we use preprocessors to support multiple versions just like MS does. 
If a version falls out of support (3-Version policy) we create a support/Major branch to be able to support it on demand

We use AzureDevOps Jobs to support multi-version builds
The yaml looks something like this:
```yml
resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps.Pipelines  

variables:
- group: 'al.builds' # variable group  

jobs:
- job: current
  steps:
  - template: AL.Template.Steps.yml@templates
    parameters:
      RunAppSource: true
      Version: 'current'
      CreateBetaApp: ${{ parameters.CreateBetaAppCurrent }}    

- job: prev1
  dependsOn: current
  steps:
  - template: AL.Template.Steps.yml@templates
    parameters:
      Version: 'prev1'
      CreateBetaApp: ${{ parameters.CreateBetaAppPrev1 }}

- job: prev2
  dependsOn: prev1
  steps:
  - template: AL.Template.Steps.yml@templates
    parameters:
        Version: 'prev2'
        CreateBetaApp: ${{ parameters.CreateBetaAppPrev2 }}
```

current, prev1, prev2 are the version identifiers we use for the 3 supported versions. 

We also use a "project.json" adapted from freddys initial approach, there we configure the versions/artifacts used for the identifiers:
```
       {
            "version": "current",
            "buildNumber": "22.0",
            "artifact": "bcartifacts/sandbox/22.0/ch",
            "alwaysPull": true
        },     
        {
            "version": "prev1",
            "buildNumber": "21.0",
            "artifact": "bcartifacts/sandbox/21.0/ch",
            "alwaysPull": true
        },
        {
            "version": "prev2",
            "buildNumber": "20.0",
            "artifact": "bcartifacts/sandbox/20.0/ch",
            "alwaysPull": true
        }
```

nextminor and nextmajor builds are configured there too and run every week to ensure compatibility. 

Code is structured like this:
- config
  - apps
    - app1
      - app.22.0.json
      - app.21.0.json
      - app.20.0.json
- app1
  - *.al source code 

In the build pipelien we copy the appropriate app.json from the config folder to the source folder for every stage 

I hope this may help you. Feel free to ask about details on this.
