### ISSUE TITLE
Version 6.0.1 Compile-AppInBCContainer throws error with BC15 images when importing System.IO.Packaging.dll

### ISSUE THREAD

**Issue by FWI-95** [microsoft/navcontainerhelper#3265]
**Describe the issue**
With the new version 6.0.1 our Pipelines suddenly started failing with BC15 images with the following error:

##[error]Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 
'C:\build\vsix\extension\bin\System.IO.Packaging.dll' because it does not exist."

We can't seem to find why this is caused only on our Agent-Hosts, but it appears to be connected to the last change with version 6.0.1 in the Script Compile-AppInBCContainer at line 521:
Add-Type -Path (Join-Path $alcPath System.IO.Packaging.dll)

![image](https://github.com/microsoft/navcontainerhelper/assets/46918703/62558016-449e-4c8f-9afc-487cac60ac52)

While we can't find to see any clear indication of what the error is causing, my suspicion is that the try-catch could behave differently on Azure Agents.

** Attachments **
[PipelineErrorBcContainerHelper.zip](https://github.com/microsoft/navcontainerhelper/files/13567566/PipelineErrorBcContainerHelper.zip)

**Scripts used to create container and cause the issue**
```
Attachments scripts\Compile-App.ps1.txt
Attachments scripts\Create-Container.ps1.txt
```

** YAML section **
```
        - task: PowerShell@2
          displayName: 'Create Container ${{ version.Container.containerName }}'
          timeoutInMinutes: 60
          env:
            Password: $(Password)
            LicenseFile: $(LicenseFile)
          inputs:
            targetType: filePath
            filePath: 'Comsol.Build.Pipelines\buildscripts\Create-Container.ps1'
            arguments: '-imageName "${{ version.Container.Imagename }}" 
                        -ContainerMajor "${{ version.Container.Major }}" 
                        -ContainerMinor "${{ version.Container.Minor }}" 
                        -ContainerTarget "${{ version.Container.Target }}" 
                        -ContainerCountry "${{ version.Container.Country }}" 
                        -ContainerStorageAccount "${{ version.Container.storageAccount }}" 
                        -ContainerSasToken "${{ version.Container.sasToken }}" 
                        -versionName "${{ version.versionName }}"'
            failOnStderr: true

...

          - task: PowerShell@2
            displayName: 'Compile ${{ appFolder }}'
            timeoutInMinutes: 20
            env:
              Password: $(Password)
            inputs:
              targetType: filePath
              filePath: 'Comsol.Build.Pipelines\buildscripts\Compile-App.ps1'
              arguments: '-appFolder ${{ appFolder }} -versionName ${{ version.versionName }}'
              # failOnStderr: true
```
**Full output of scripts**
```
Full logs and direct comparison between version 6.0.0 and 6.0.1 is in the attachments:
v600
v601

Compile-AppInBCContainer -containerName cmt15711981 -credential System.Management.Automation.PSCredential -appProjectFolder (Join-Path C:\BA\CBAB1\_work\52\s\Comsol.MigrationTool.OnPrem\15_7 MigrationTool) -appSymbolsFolder C:\BA\CBAB1\_work\52\s\Comsol.MigrationTool.OnPrem\15_7\.alPackages -appOutputFolder C:\BA\CBAB1\_work\52\a\15_7\MigrationTool -UpdateSymbols: #-AzureDevOps:(AzureDevOps -eq  AzureDevOps)
BcContainerHelper version 6.0.1
Setting usePsSession = False
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Using Symbols Folder: C:\BA\CBAB1\_work\52\s\Comsol.MigrationTool.OnPrem\15_7\.alPackages
Processing dependency Microsoft_Application_15.0.0.0 ()
Downloading symbols: Microsoft_Application_15.7.43293.0.app
Url : http://172.24.16.79:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=15.0.0.0&tenant=default
Downloading using WebClient
Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\build\vsix\extension\bin\System.IO.Packaging.dll' because it does not exist."

Container Free Physical Memory: 9.1Gb

Services in container cmt15711981:
- MicrosoftDynamicsNavServer$BC is Running
- MSSQL$SQLEXPRESS is Running

Compile-AppInBCContainer Telemetry Correlation Id: 59cf5194-70a0-40af-8649-6a322d54944c
##[error]Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 
'C:\build\vsix\extension\bin\System.IO.Packaging.dll' because it does not exist."
In C:\Program 
Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.1\ContainerHandling\Invoke-ScriptInNavContainer.ps1:285 
Zeichen:25
+                         throw $errorMessage
+                         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot bind par...oes not exist.":String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path  
   'C:\build\vsix\extension\bin\System.IO.Packaging.dll' because it does not exist."
##[error]PowerShell exited with code '1'.
```

**Screenshots**

**Additional context**
- It seems to be affecting all BC15 images
- BC16 and upwards are working fine
- Reverting back to version 6.0.0 solves the issue.
- It does run succesfully on local machines
- Removing failOnStderr in YAML task does not seem to be affecting the error
