### ISSUE TITLE
CI.yml: Login to bcinsider

### ISSUE THREAD

**Issue by achim-t** [microsoft/navcontainerhelper#740]
When going for the "nextminor" version, the pipeline throws an error on the 'Login to bcinsider repository':

`##[error]docker : WARNING! Using --password via the CLI is insecure. Use --password-stdin.`

Is there a workaround?

Additionally, having the version variable in the yaml prevents setting it to something else on build time.

I want to run regularly scheduled builds for nextminor and nextmajor. Is there a different solution then having three (including normal CI) pipelines that differ only in the version variable?

**Comment by freddydk** [comment]
I ended up doing this in my BingMaps sample:

```
    - task: CmdLine@2
      displayName: 'Login to bcinsider repository'
      condition: and(succeeded(),or(eq(variables['version'],'nextminor'),eq(variables['version'],'nextmajor')))
      inputs:
        script: 'echo $(bcinsiderPassword) | docker login "bcinsider.azurecr.io" -u "$(bcInsiderUsername)" --password-stdin'
        failOnStderr: false
```

and having bcInsiderPassword and bcInsiderUsername as variables.
I think that works. Will move that to the helloworld repo as well.

**Comment by achim-t** [comment]
Thanks, that works. Usage of CmdLine instead of PowerShell tripped me up for a minute, though.

Do you have thoughts on the rest of my question?
> Additionally, having the version variable in the yaml prevents setting it to something else on build time.
> 
> I want to run regularly scheduled builds for nextminor and nextmajor. Is there a different solution then having three (including normal CI) pipelines that differ only in the version variable?

**Comment by freddydk** [comment]
In the bingmaps sample (https://dev.azure.com/businesscentralapps/BingMaps) i also use 3 different pipelines. I think you can include yaml files in yaml files to minimize double work (basically only having a few things in the main .yml file) I haven't looked into that.

Not sure I understand why you would set the build to something else at build time - build version should always increase.

Alternatively you can set things in a PowerShell script.

**Comment by achim-t** [comment]
I was trying to use the same yaml file for different pipelines and just setting the version to 'current', 'nextminor' or 'nextmajor' in the variable of each pipeline. The line `version: "current"` in the yaml file prevents that variable to be set.

**Comment by freddydk** [comment]
You could move that to a variable and make it settable at build time I guess.

**Comment by achim-t** [comment]
Including .yml files is quite easy:
`CI.yml:`
```yml
stages:
- stage: Build
  jobs:
  - job: Build
    variables:
      build.clean: all
      platform: x64
    steps:
    - template: steps.yml
```
`steps.yml:` 
```yml
steps:
- task: PowerShell@2
  displayName: 'Reading Settings'
  inputs:
    targetType: filePath
    filePath: 'scripts\Read-Settings.ps1'
    arguments: '-appVersion "$(appVersion).$(appBuild).$(appRevision)"'
    failOnStderr: true      
- task: CmdLine@2
  displayName: 'Login to bcinsider repository'
  condition: and(succeeded(),or(eq(variables['version'],'nextminor'),eq(variables['version'],'nextmajor')))
  inputs:
    targetType: inline
    script: 'echo $(bcinsiderPassword) | docker login "bcinsider.azurecr.io" -u "$(bcInsiderUsername)" --password-stdin'
    failOnStderr: false
[...]
```

You can even have the steps as a template in another repo.
`CI.yml:`
```yml
resources:
  repositories:
    - repository: templates
      type: git
      name: OtherRepo
      
stages:
- stage: Build
  jobs:
  - job: Build
    variables:
      build.clean: all
      platform: x64

    steps:
    - template: steps.yml@templates
```

If you want to have the scripts in another Repo as well, you have to copy them during the build in order to use them.

`steps.yml`
```yml
steps:
- task: PowerShell@2
  displayName: Get Scripts from Template
  inputs:
    targetType: inline
    script: |
      try { git clone -b master https://azuredevops:$($env:token)@dev.azure.com/DEVLB/Produktplanung%20LIS/_git/Template $(Build.SourcesDirectory)\scripts\external } catch {}
      copy-item -path .\scripts\external\*.ps1 -destination .\scripts
      exit 0
  env:
    token: $(System.AccessToken)
- task: PowerShell@2
  displayName: 'Reading Settings'
  inputs:
    targetType: filePath
    filePath: 'scripts\Read-Settings.ps1'
    arguments: '-appVersion "$(appVersion).$(appBuild).$(appRevision)"'
    failOnStderr: true   
```
(For some reason `git clone` throws an error but the script files are there. To make the task succeed I use a try/catch and `exit 0`)

**Comment by gintuoklis** [comment]
I solved the same problem by adding this task to my YML

```
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: YourAzureRegistryServiceConnection
```

you need to create YouAzureRegistryServiceConnection first under your project settings

https://_your.visualstudio.com_/DefaultCollection/_your_project_name_/_settings/adminservices

It's secure and simple
